config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :bugcycles do
    resources :suggestions, only: [:new, :create, :destroy]
  end

  get '/bugcycles/:category_name/:category_id', to: 'bugcycles#by_category', as: 'bugcycles_by_category'

  post '/bugcycle/:id/used/:url', to: 'bugcycles#used', as: 'used_bugcycle'

  put '/bugcycle/:bugcycle_id/approve_suggestion/:suggestion_id', to: 'suggestions#approve', as: 'approve_suggestion'
  delete '/bugcycle/:bugcycle_id/destroy_suggestion', to: 'suggestions#destroy_all', as: 'destroy_all_suggestions'

  root 'main#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all 

    if user && user.admin?
      can :dashboard, :all
      can :access, :rails_admin
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bugcycle.rb
class Bugcycle < ApplicationRecord
  
  has_many :suggestions
  
  belongs_to :user
  belongs_to :category

  validates :name, uniqueness: true

  mount_uploader :image, ImageUploader

  scope :search, -> search { where('name LIKE ? or description LIKE ?', "%#{search}%", "%#{search}%") }

  def self.not_used(useds)
    ids = []

    useds.each do |used|
      ids << used.bugcycle_id
    end

    return where.not(id: ids)
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :bugcycles
  has_many :suggestions
end

app/models/suggestion.rb
class Suggestion < ApplicationRecord
  belongs_to :bugcycle
  belongs_to :user
  belongs_to :category

  mount_uploader :image, ImageUploader
end

app/models/used.rb
class Used < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :bugcycles
  has_many :suggestions
  has_many :useds

  as_enum :role, admin: 1, user: 0
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bugcycles_controller.rb
class BugcyclesController < ApplicationController
  before_action :set_bugcycle, only: [:show, :edit, :update, :destroy]

  def index
    used = current_user.useds

    if params[:search]
      @bugcycles = current_user.bugcycles.not_used(used).search(params[:search]).paginate(page: params[:page], per_page: 12)
    else
      @bugcycles = current_user.bugcycles.not_used(used).paginate(page: params[:page], per_page: 12)
    end
  end

  def show; end

  def new
    @bugcycle = Bugcycle.new
  end

  def create
    @bugcycle = Bugcycle.new(bugcycle_params)

    if @bugcycle.save
      redirect_to bugcycles_url
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @bugcycle.update_attributes(bugcycle_params)
      redirect_to bugcycles_url
    else
      render 'edit'
    end
  end

  def destroy
    if @bugcycle.destroy
      redirect_to bugcycles_url
    else
      render 'index'
    end
  end

  def used
    Used.create(bugcycle_id: params[:id], user_id: current_user.id)
    redirect_to params[:url]
  end

  def by_category
    @bugcycles = Bugcycle.where(category_id: params[:category_id])
  end

  private

  def set_bugcycle
    @bugcycle = Bugcycle.find(params[:id])
  end

  def bugcycle_params
    params.require(:bugcycle).permit(:name, :description, :image, :category_id).merge(user_id: current_user.id)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    if user_signed_in?
      used = current_user.useds

      if params[:search]
        @bugcycles = Bugcycle.not_used(used).search(params[:search]).paginate(page: params[:page], per_page: 12)
      else
        @bugcycles = Bugcycle.not_used(used).paginate(page: params[:page], per_page: 12)
      end
    else
      if params[:search]
        @bugcycles = Bugcycle.search(params[:search]).paginate(page: params[:page], per_page: 12)
      else
        @bugcycles = Bugcycle.paginate(page: params[:page], per_page: 12)
      end
    end
  end
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  before_action :set_bugcycle

  def approve
    suggestion = Suggestion.find(params[:suggestion_id])

    if @bugcycle.update_attributes(suggestion.attributes.except('id', 'bugcycle_id', 'user_id'))
      suggestion.destroy
      redirect_to bugcycles_url
    else
      redirect_to bugcycle_url(@bugcycle)
    end
  end

  def new
    @categories = Category.all
    @suggestion = @bugcycle.suggestions.new
  end

  def create
    @suggestion = @bugcycle.suggestions.new(suggestion_params)

    if @suggestion.save
      redirect_to root_path, notice: 'Suggestion send...'
    else
      render 'new'
    end
  end

  def destroy
    @bugcycle.suggestions.find(params[:id]).destroy
    redirect_to bugcycle_url(@bugcycle)
  end

  def destroy_all
    @bugcycle.suggestions.delete_all
    redirect_to bugcycle_url(@bugcycle)
  end

  private

  def set_bugcycle
    @bugcycle = Bugcycle.find(params[:bugcycle_id])
  end

  def suggestion_params
    params.require(:suggestion).permit(:name, :description, :image, :category_id).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugcycles_helper.rb
module BugcyclesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def categories
    Category.all
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
  def block_suggestion(bugcycle ,user_id)
    count = 0
    bugcycle.suggestions.each do |suggestion|

      count += 1 if suggestion.user_id == user_id

      break if count > 0
    end

    return count > 0 ? false : true
  end
end

app/views/bugcycles/_form.html.haml
.create-update-bicycle-form
  - if @bugcycle.errors.any?
    - @bugcycle.errors.full_messages.each do |error|
      Errors:
      = error
  = form_for @bugcycle, html: { multipart: true } do |f|
    .form-group
      = f.label :name
      %br
      = f.text_field :name, class: 'form-control'
    .form-group
      = f.label :description
      %br
      = f.text_area :description, class: 'form-control'
    .form-group
      = f.label :category_id
      %br
      = f.collection_select :category_id, categories, :id, :category, {}, { class: 'form-control' }
    .form-group
      .input-group
        %span.input-group-btn
          = f.label :image, class: 'btn btn-default btn-file js-load-image'
        %span#image-url.form-control
      = f.file_field :image
    = f.submit 'Save', {class: 'btn btn-default save'}
    :javascript
      $(document).ready(function(){
        $('#bugcycle_image').change(function(e){
          var value = e.target.files[0].name;
          $('#image-url').text(value);
        });
      })

app/views/bugcycles/by_category.html.haml
.text-center
  %h1
    = params[:category_name]
%input#search.form-control{ type: 'text', placeholder: 'Search' }
.js-bugcycles
  .container-fluid
    .row
      - @bugcycles.each do |bugcycle|
        .col-md-4.col-xs-6
          .thumbnail
            = image_tag(bugcycle.image.url) if bugcycle.image?
            %p.name
              Name:
              = bugcycle.name
            %p.category
              Category:
              = bugcycle.category.name
            .description
              Description:
              .pre-scrollable
                = bugcycle.description
            .suggestion
              - if user_signed_in? && current_user.id != bugcycle.user_id && block_suggestion(bugcycle, current_user.id)
                = link_to 'Suggestion', new_bugcycle_suggestion_url(bugcycle), class: 'btn btn-default'

app/views/bugcycles/edit.html.haml
.text-center
  %h1 
    Edit record

= render 'form', collection: @bugcycle

app/views/bugcycles/index.html.haml
.my-bicycles
  %h1
    My Bicycles
  %input#search.form-control{ type: 'text', placeholder: 'Search' }
  .js-bugcycles
    = link_to 'New', new_bugcycle_url, class: 'btn btn-default btn-new'
    .container-fluid
      .row
        - @bugcycles.each do |bugcycle|
          .col-md-4.col-xs-6
            .thumbnail
              = image_tag(bugcycle.image.url) if bugcycle.image?
              %p.name
                Bicycle:
                = bugcycle.name
              %p.category
                Category:
                = bugcycle.category.name
              .description
                Description:
                .pre-scrollable
                  = bugcycle.description
              = link_to 'Edit', edit_bugcycle_url(bugcycle), class: 'btn btn-default'
              = link_to 'Used', used_bugcycle_url(bugcycle, bugcycles_url), method: :post, data: { confirm: 'Are you sure?' }, class: 'btn btn-default'
              = link_to 'Destroy', bugcycle_url(bugcycle), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
              - if bugcycle.suggestions.count > 0
                = link_to bugcycle_url(bugcycle), { class: 'btn btn-default suggestions' } do
                  Suggestion
                  %span.badge
                    = bugcycle.suggestions.count

= will_paginate @bugcycles, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer

app/views/bugcycles/new.html.haml
.text-center
  %h1
    Bugcycle new

= render 'form', collection: @bugcycle

app/views/bugcycles/show.html.haml
.text-center
  %h1
    Suggestions
.container-fluid
  .row
    .col-xs-4.col-xs-offset-4
      - if @bugcycle.suggestions.count > 1
        = link_to 'Delete all!', destroy_all_suggestions_url(@bugcycle), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
    - @bugcycle.suggestions.each do |suggestion|
      .col-xs-4.col-xs-offset-4
        .thumbnail
          = image_tag(suggestion.image.url) if suggestion.image?
          %p.name
            Bicycle:
            = suggestion.name
          %p.category
            Category:
            = suggestion.category.category
          .description
            Description:
            .pre-scrollable
              = suggestion.description
          = link_to 'Approve', approve_suggestion_url(@bugcycle, suggestion), method: :put, class: 'btn btn-default'
          = link_to 'Delete', bugcycle_suggestion_url(@bugcycle, suggestion), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

app/views/categories/show.html.haml
.text-center
  %h1
    = @category.category
%input#search.form-control{ type: 'text', placeholder: 'Search' }
.js-bugcycles
  .container-fluid
    .row
      - @bugcycles.each do |bugcycle|
        .col-md-4.col-xs-6
          .thumbnail
            = image_tag(bugcycle.image.url) if bugcycle.image?
            %p.name
              Name:
              = bugcycle.name
            %p.category
              Category:
              = bugcycle.category.category
            .description
              Description:
              .pre-scrollable
                = bugcycle.description
            .suggestion
              - if user_signed_in? && current_user.id != bugcycle.user_id && block_suggestion(bugcycle, current_user.id)
                = link_to 'Suggestion', new_bugcycle_suggestion_url(bugcycle), class: 'btn btn-default'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CoaxBugcycle
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    :javascript
      document.addEventListener('DOMContentLoaded', function(){
        document.getElementById('search').addEventListener('keyup', delay(function(){
          search();
        }, 500));

        $('.page-link').on('click', function() {
          $(this).attr('href', function(){
            link = document.location.search;
            newLink = '';

            if(link.includes('search')) {
              var url = link.split('&');
              newLink = this.href + '&' + url[1]
            } else {
              newLink = this.href;
            }

            return newLink;
          });
        });
      });

  %body
    .nav.navbar-default
      .container-fluid
        .navbar-header
          .navbar-brand
            Bugcycle
        %ul.nav.navbar-nav
          %li
            = link_to 'Main page', root_url
          %li
            - if user_signed_in?
              = link_to 'My bicycles', bugcycles_url
          %li
            - if user_signed_in? && current_user.admin?
              = link_to 'Admin', rails_admin_url
          %li.dropdown
            %a.dropdown-toggle{ href: '#', 'data-toggle' => 'dropdown', role: 'button','aria-haspopup' => 'true', 'aria-expanded' => 'false' }
              Categories
              %span.caret
            %ul.dropdown-menu
              - categories.each do |category|
                %li
                  = link_to category.name, bugcycles_by_category_url(category.name ,category.id)
        .nav.navbar-right
          - if !user_signed_in?
            = link_to 'Sign In', new_user_session_url, class: "btn btn-default navbar-btn"
            = link_to 'Sign Up', new_user_registration_url, class: "btn btn-default navbar-btn"
          = button_to 'Sign Out', destroy_user_session_url, method: :delete, class: "btn btn-default navbar-btn" if user_signed_in?
    = yield

app/views/main/index.html.haml
%input#search.form-control{ type: 'text', placeholder: 'Search' }
.js-bugcycles
  .container-fluid
    .row
      - @bugcycles.each do |bugcycle|
        .col-md-4.col-xs-6
          .thumbnail
            = image_tag(bugcycle.image.medium_image) if bugcycle.image?
            %p.name
              Name:
              = bugcycle.name
            %p.category
              Category:
              = bugcycle.category.name
            .description
              Description:
              .pre-scrollable
                = bugcycle.description
            - if user_signed_in?
              = link_to 'Used', used_bugcycle_url(bugcycle, root_url), method: :post, data: { confirm: 'Are you sure?' }, class: 'btn btn-default'
            - if user_signed_in? && current_user.id != bugcycle.user_id && block_suggestion(bugcycle, current_user.id)
              = link_to 'Suggestion', new_bugcycle_suggestion_url(bugcycle), class: 'btn btn-default'
= will_paginate @bugcycles, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer

app/views/suggestions/new.html.haml
.create-update-bicycle-form
  .text-center
    %h1
      Suggestion
    = form_for [@bugcycle, @suggestion], html: { multipart: true } do |f|
      .form-group
        = f.label :name
        %br
        = f.text_field :name, class: 'form-control'
      .form-group
        = f.label :description
        %br
        = f.text_area :description, class: 'form-control'
      .form-group
        = f.label :category_id
        %br
        = f.collection_select :category_id, @categories, :id, :category, {}, { class: 'form-control' }
      .form-group
        .input-group
          %span.input-group-btn
            = f.label :image, class: 'btn btn-default btn-file js-load-image'
          %span#image-url.form-control
        = f.file_field :image
      = f.submit 'Save', {class: 'btn btn-default save'}
      :javascript
        $(document).ready(function(){
          $('#suggestion_image').change(function(e){
            var value = e.target.files[0].name;
            $('#image-url').text(value);
          });
        })